project:
  type: website

website:
  title: "opengeohub23"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - tidy.qmd
      - href: tidy-slides.qmd
        text: "Tidy geographic data: slides"
      - href: osm.qmd
        text: "Large OSM datasets"
      - href: osm-slides.qmd
        text: "Large OSM datasets: slides"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

