project:
  type: website

website:
  title: "opengeohub23"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - tidy.qmd
      - osm.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



